version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_compose_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nerdery_ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    tty: true

  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    tty: true

volumes:
  postgres_data:
